### ISSUE TITLE
Forme d'écriture "inclusive" ou classique

### ISSUE THREAD

**Issue by Aliocha-Iordanoff** [holacracyone/Holacracy-Constitution-5.0-FRENCH#8]
Dans la version actuelle de la traduction, il y a parfois des abréviations inclusives comme : 
- Associé(e)s
- il/elle
mais aussi des endroits où la forme classique au masculin est utilisée.
Par exemple, "Facilitateur" ou "le Secrétaire est chargé d’organiser", ou "l’ensemble des Associés".

Il me semble que pour un texte écrit avec autant de rigueur qu'une constitution, ce serait intéressant de faire un choix, pourquoi pas avec le parti pris de l'écriture inclusive, et de s'y tenir dans l'ensemble du texte. 

Qu'en dis-tu @bernardmariechiquet ?

Si c'est le choix de l'écriture inclusive qui est retenu, je crois que l'utilisation du point médian est plus usité que la parenthèse alternative. 
Sinon, le texte étant souvent perçu comme complexe, faire le choix de la lisibilité avec une écriture classique se défend bien me semble-t-il.

**Comment by bernardmariechiquet** [comment]
Je pense que la question sous-jacente liée à la parité est une vraie question et que, par exemple la fameuse règle du masculin l'emporte sur le féminin devrait être revisitée.
Donc pour répondre à ta question, je suis pour l'évolution vers l'écriture inclusive.

Lors de la traduction de la version 5.0, je me suis posé la question de la façon d'écrire - que je ne m'était pas posé en 2016 lors de la version 4.1 parce-que cette évolution légitime est encore récente.

Après se pose la question de la forme de l'écriture inclusive. J'observe que si l'écriture inclusive avec le point median semble se développer dans certaines sphères, pour autant, elle n'est pas admise (encore) sur le plan légale, ni reconnue tant pas l'éducation nationale que par l'académie française.

J'ai donc choisi l'option d'évoluer vers l'écriture inclusive classique. Avec probablement certains manques que tu as pointés.

Il y a des limites à ce stade, jusqu'ou aller . Tu cites Facilitateur et Secrétaire. On pourrait aussi parler de Leader de cercle/rôle....

Il faudrait se poser certains principes/règles sur le sujet.

Je vais revoir le texte sur le sujet.

**Comment by Aliocha-Iordanoff** [comment]
Je partage cet intérêt pour faire évoluer les formes d'écriture vers l'inclusivité.

S'agissant de ce texte, comme c'est une constitution, et à ce titre un texte d'une grande rigueur et précision, je serais favorable à ce que les choix d'écriture soient constants tout au long du texte, pour éviter toute confusion. La signification précise d'un texte qui serait parfois inclusif, parfois non, me semble bizarre. 

Pour le choix de la forme elle-même, le débat sur les parenthèses, ou le point médiant concerne toujours l'idée d'utiliser une forme abrégée pour inclure le féminin dans les noms et les adjectifs. 
Cette constitution n'utilise aucune forme abrégée par ailleurs. Et comme il n'y a pas d'enjeu à économiser de la place à l'écran, ni de l'ancre sur le papier en raccourcissant la taille des phrases, je trouverais intéressant que la forme écrite soit la forme qui se prononce à la lecture. Donc concrètement une écriture incluse in extenso, si tu décides de maintenir ce choix d'une écriture inclusive.

Par exemple : 
- Chaque Cercle peut désigner une personne pour être son « Facilitateur » ou sa « Facilitatrice »
- Chaque Cercle peut désigner un ou une « Secrétaire » ...

Je comprends le souhait de ne pas "faire lourd" aussi. 

Je soutiendrais un choix clair et assumé pour une forme ou une autre plus qu'un hybride.

**Comment by ocompagne** [comment]
C'est evidemment subjectif, mais j'ai eu l'occasion recemment de regarder la traduction francaise de la constitution avec un oeil sur cette question, et la solution "hybride" actuelle m'a paru assez équilibrée et élégante. Justement parce qu'elle n'ajoutait pas vraiment de lourdeur a la lecture et reste tres claire. Je trouverais dommage de revenir a une forme entierement classique avec le masculin partout. 

Pour ma part, le coût de rajouter des mots n'est pas tant la depense de papier ou d'encre que la longueur des phrases et difficulté de lecture.
